<?php

/**
 * @file
 * Contains mapbox.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mapbox_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mapbox module.
    case 'help.page.mapbox':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mapbox Drupal 8 integration.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mapbox_theme() {
  return [
    'mapbox' => [
      'render element' => 'children',
    ],
  ];
}
