mapbox.mapbox.*:
  type: config_entity
  label: 'Mapbox config'
  mapping:
    id:
      type: machine_name
      label: 'ID'
    label:
      type: label
      label: 'Label'
    access_token:
      type: string
      label: 'Access Token'
    style:
      type: string
      label: 'Style'
    center:
      type: mapping
      label: 'Center'
      mapping:
        x:
          type: float
          label: 'Center X'
        y:
          type: float
          label: 'Center Y'
    zoom:
      type: float
      label: 'Zoom'
field.formatter.settings.mapbox:
  type: mapping
  label: 'Mapbox'
  mapping:
    mapbox_id:
      type: string
      label: 'Mapbox ID'
